version: "3.9"

services:
  django-app:
    networks:
      - default
    build:
      context: ./backend-python/django_backend/user_services
      dockerfile: Dockerfile
    container_name: jajancuy-sso
    volumes:
      - ./backend-python/django_backend/user_services:/jajancuy/django-sso
    restart: always
