version: "3.9"

services:
  django-app:
    networks:
      - default
    build:
      context: ./backend-python/django_backend/user_services
      dockerfile: Dockerfile
    container_name: jajancuy-sso
    volumes:
      - ./backend-python/django_backend/user_services:/jajancuy/django-sso
    ports:
      - "5000:5000"  # Memetakan port 5000 di host ke port 5000 di kontainer
    restart: always
