# .air.toml
root = "."
tmp_dir = "tmp"

[build]
cmd = "go build -v -o tmp/main.exe cmd/main.go"
include = ["*.go"]
exclude = ["tmp/*"]
delay = 1000

[log]
time = true
level="debug"
prefix = "[AIR]"
color = "yellow"
file="app.log"

[watch]
dir = "."
include = ["*.go"]
exclude = ["tmp/*"]
