name: CI/CD Connect to VPS

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout Code
      uses: actions/checkout@v3

    - name: Deploy to VPS using SSH
      env:
        PRIVATE_KEY: ${{ secrets.SSH_PRIVATE_KEY }}
        VPS_USER: ${{ secrets.VPS_USER }}
        VPS_HOST: ${{ secrets.VPS_HOST }}
      run: |
        # Setup SSH
        mkdir -p ~/.ssh
        echo "$PRIVATE_KEY" > ~/.ssh/id_rsa
        chmod 600 ~/.ssh/id_rsa
        ssh-keyscan -H $VPS_HOST >> ~/.ssh/known_hosts

        # SSH into VPS and execute commands
        ssh $VPS_USER@$VPS_HOST << 'EOF'
          # Navigate to project directory
          cd /var/www/jajancuy-app-backend

          # Stop any running containers (if applicable)
          echo "Stopping running containers..."
          docker-compose down || true

          # Pull the latest changes from Git
          echo "Pulling latest changes from Git..."
          git pull origin main

          # Build and start Docker containers
          echo "Building and starting Docker containers..."
          docker-compose up --build -d

          # Clean up old Docker images
          echo "Cleaning up unused Docker images..."
          docker image prune -f

          # Verify application is running (optional)
          echo "Verifying deployment..."
          curl --fail http://localhost:5000 || (echo "Application failed to start!" && exit 1)
        EOF
