name: CI/CD Connect to VPS

on:
  push:
    branches:
      - main

jobs:
  deploy:
    name: Deploy project with Docker
    permissions:
      deployments: write
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2
        with:
          ref: main
          token: ${{ secrets.PERSONAL_GITHUB_TOKEN }}

      - name: Create GitHub deployment
        uses: chrnorm/deployment-action@v2
        id: deployment
        with:
          token: '${{ github.token }}'
          environment: production

      - name: Set up SSH Key and Deploy my App on Server
        uses: appleboy/ssh-action@master
        env:
          GITHUB_TOKEN: ${{ secrets.PERSONAL_GITHUB_TOKEN }}
        with:
          host: ${{ secrets.VPS_HOST }}
          username: ${{ secrets.VPS_USER }}
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          passphrase: ${{ secrets.SSH_PASSPHRASE }}
          port: 22
          script: |
            # Setup GitHub Token for authentication
            git config --global url."https://${{ secrets.PERSONAL_GITHUB_TOKEN }}:@github.com".insteadOf "https://github.com"
            
            # Navigate to the project directory
            cd /var/www/jajancuy-app-backend

            # Pull the latest changes from Git
            echo "Pulling latest changes from Git..."
            git pull origin main

            # Navigate to the docker compose
            cd /var/www/jajancuy-app-backend/backend

            # Stop any running containers (if applicable)
            echo "Stopping running containers..."
            docker-compose down || true

            # Build and start Docker containers
            echo "Building and starting Docker containers..."
            docker-compose up --build -d

            # # Clean up old Docker images to save space
            # echo "Cleaning up unused Docker images..."
            # docker image prune -f

            # Verify that the application is running
            echo "Verifying deployment..."
            curl --fail http://localhost:5000 || (echo "Application failed to start!" && exit 1)
