name: JAJANCUY API CI CD

on:
    push:
      branches:
        - main
jobs:
    deploy:
      runs-on: ubuntu-latest
  
      steps:
      - name: Checkout Code
        uses: actions/checkout@v3
  
      - name: Setup Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'
  
      - name: Install Dependencies
        working-directory: backend/backend-python/django_backend/user_services
        run: |
          python -m venv .venv
          source .venv/bin/activate
          pip install -r ../../requirements.txt
  
      - name: Setup Environment Variables
        working-directory: backend/backend-python/django_backend/user_services
        run: |
          echo "SECRET_APP=${{ secrets.DJANGO_SECRET_APP }}" >> .env
          echo "RUN_PORT=${{ secrets.DJANGO_RUN_PORT }}" >> .env

          echo "DB_NAME=${{ secrets.DB_NAME_SSO }}" >> .env
          echo "DB_USER=${{ secrets.DB_USER_SSO }}" >> .env
          echo "DB_PASSWORD=${{ secrets.DB_PASSWORD_SSO }}" >> .env
          echo "DB_HOST=${{ secrets.DB_HOST_SSO }}" >> .env
          echo "DB_PORT=${{ secrets.DB_PORT_SSO }}" >> .env

          echo "CLIENT_GOOGLE_ID=${{ secrets.CLIENT_GOOGLE_ID }}" >> .env
          echo "CLIENT_GOOGLE_SECRET=${{ secrets.CLIENT_GOOGLE_SECRET }}" >> .env

          echo "DEFAULT_FROM_EMAIL=${{ secrets.DEFAULT_FROM_EMAIL }}" >> .env
          echo "EMAIL_HOST=${{ secrets.EMAIL_HOST }}" >> .env
          echo "EMAIL_PORT=${{ secrets.EMAIL_PORT }}" >> .env
          echo "EMAIL_USE_TLS=${{ secrets.EMAIL_USE_TLS }}" >> .env
          echo "EMAIL_HOST_USER=${{ secrets.EMAIL_HOST_USER }}" >> .env
          echo "EMAIL_HOST_PASSWORD=${{ secrets.EMAIL_HOST_PASSWORD }}" >> .env

          echo "FRONTEND_URL=${{ secrets.FRONTEND_URL }}" >> .env
  
      - name: Run Migrations
        working-directory: backend/backend-python/django_backend/user_services
        run: |
          source .venv/bin/activate
          python manage.py migrate
  
      - name: Collect Static Files
        working-directory: backend/backend-python/django_backend/user_services
        run: |
          source .venv/bin/activate
          python manage.py collectstatic --noinput
          - name: Deploy to Server
          run: |
            echo "Deploying to server..."
